services:
  rest.controller:
    class: Tardigrades\SectionField\Api\Controller\RestController
    arguments:
      - '@section_field.create.section'
      - '@section_field.read.section'
      - '@section_field.delete.section'
      - '@section_field.form'
      - '@section_field.manager.doctrine.section_manager'
      - '@request_stack'
