services:
  section_field.manager.doctrine.application_manager:
    class: Tardigrades\SectionField\Service\DoctrineApplicationManager
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@section_field.manager.doctrine.language_manager'
    tags: [sf.manager]

  section_field.manager.doctrine.language_manager:
    class: Tardigrades\SectionField\Service\DoctrineLanguageManager
    arguments:
      - '@doctrine.orm.entity_manager'
    tags: [sf.manager]

  section_field.manager.doctrine.section_manager:
    class: Tardigrades\SectionField\Service\DoctrineSectionManager
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@section_field.manager.doctrine.field_manager'
    tags: [sf.manager]

  section_field.manager.doctrine.field_type_manager:
    class: Tardigrades\SectionField\Service\DoctrineFieldTypeManager
    arguments:
      - '@doctrine.orm.entity_manager'
    tags: [sf.manager]

  section_field.manager.doctrine.field_manager:
    class: Tardigrades\SectionField\Service\DoctrineFieldManager
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@section_field.manager.doctrine.field_type_manager'
      - '@section_field.manager.doctrine.language_manager'
    tags: [sf.manager]
