services:
  install.field.type.command:
    class: Tardigrades\Command\InstallFieldTypeCommand
    arguments:
      - '@doctrine.orm.entity_manager'

  update.field.type.command:
    class: Tardigrades\Command\UpdateFieldTypeCommand
    arguments:
      - '@doctrine.orm.entity_manager'

  delete.field.type.command:
    class: Tardigrades\Command\DeleteFieldTypeCommand
    arguments:
      - '@doctrine.orm.entity_manager'

  create.section.command:
    class: Tardigrades\Command\CreateSectionCommand
    arguments:
      - '@doctrine.orm.entity_manager'

  create.field.command:
    class: Tardigrades\Command\CreateFieldCommand
    arguments:
      - '@doctrine.orm.entity_manager'
