services:
  section_field.manager.doctrine.application_manager:
    class: Tardigrades\SectionField\Service\DoctrineApplicationManager
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@section_field.manager.doctrine.language_manager'

  section_field.manager.doctrine.language_manager:
    class: Tardigrades\SectionField\Service\DoctrineLanguageManager
    arguments:
      - '@doctrine.orm.entity_manager'

  section_field.manager.doctrine.section_manager:
    class: Tardigrades\SectionField\Service\DoctrineSectionManager
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@section_field.manager.doctrine.field_manager'

  section_field.manager.doctrine.field_type_manager:
    class: Tardigrades\SectionField\Service\DoctrineFieldTypeManager
    arguments:
      - '@doctrine.orm.entity_manager'

  section_field.manager.doctrine.field_manager:
    class: Tardigrades\SectionField\Service\DoctrineFieldManager
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@section_field.manager.doctrine.field_type_manager'
      - '@section_field.manager.doctrine.language_manager'

  section_field.generator.entity_generator:
    class: Tardigrades\SectionField\Generator\EntityGenerator
    arguments:
      - '@section_field.manager.doctrine.field_manager'
      - '@section_field.manager.doctrine.field_type_manager'
      - '@section_field.manager.doctrine.section_manager'

  section_field.generator.doctrine_config_generator:
    class: Tardigrades\SectionField\Generator\DoctrineConfigGenerator
    arguments:
      - '@section_field.manager.doctrine.field_manager'
      - '@section_field.manager.doctrine.field_type_manager'
      - '@section_field.manager.doctrine.section_manager'

  section_field.generator:
    class: Tardigrades\SectionField\Generator\Generators
    arguments:
      -
        - '@section_field.generator.entity_generator'
        - '@section_field.generator.doctrine_config_generator'

  section_field.form:
    class: Tardigrades\SectionField\Form\Form
    arguments:
      - '@section_field.manager.doctrine.section_manager'
      - '@section_field.read.section'

  section_field.doctrine.create.section:
    class: Tardigrades\SectionField\Service\DoctrineSectionCreator
    arguments:
      - '@doctrine.orm.entity_manager'

  section_field.doctrine.read.section:
    class: Tardigrades\SectionField\Service\DoctrineSectionReader
    arguments:
      - '@doctrine.orm.entity_manager'

  section_field.create.section:
    class: Tardigrades\SectionField\Service\CreateSection
    arguments:
      -
        - '@section_field.doctrine.create.section'

  section_field.read.section:
    class: Tardigrades\SectionField\Service\ReadSection
    arguments:
      -
        - '@section_field.doctrine.read.section'
      - '@section_field.manager.doctrine.section_manager'

  section_field.twig.section:
    class: Tardigrades\Twig\SectionTwigExtension
    arguments:
      - '@section_field.read.section'
    tags: [twig.extension]

  section_field.twig.section_form:
    class: Tardigrades\Twig\SectionFormTwigExtension
    arguments:
      - '@section_field.manager.doctrine.section_manager'
      - '@section_field.create.section'
      - '@section_field.form'
      - '@request_stack'

    tags: [twig.extension]
